/*
 * JS for ENGLISH generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '4755af2a-9649-4082-8a4e-5a002094efea';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "SELECT",
    "location": "SELECT.html"
}, {
    "name": "MAPS",
    "location": "MAPS.html"
}, {
    "name": "LANGUAGESELECTION",
    "location": "LANGUAGESELECTION.html"
}, {
    "name": "TELUGU",
    "location": "TELUGU.html"
}, {
    "name": "HINDI",
    "location": "HINDI.html"
}, {
    "name": "ENGLISH",
    "location": "ENGLISH.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "TAMIL",
    "location": "TAMIL.html"
}];

function ENGLISH_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'ENGLISH_mobilebutton_2',
        'mobilebutton_3': 'ENGLISH_mobilebutton_3',
        'mobilebutton_4': 'ENGLISH_mobilebutton_4',
        'mobilebutton_5': 'ENGLISH_mobilebutton_5',
        'mobilebutton_6': 'ENGLISH_mobilebutton_6'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'ENGLISH';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var ENGLISH_onLoad = function() {
        ENGLISH_elementsExtraJS();
        ENGLISH_deviceEvents();
        ENGLISH_windowEvents();
        ENGLISH_elementsEvents();
    };
    // screen window events
    function ENGLISH_windowEvents() {
        $('#ENGLISH').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function ENGLISH_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function ENGLISH_elementsExtraJS() {
        // screen (ENGLISH) extra code
    };
    // screen elements handler
    function ENGLISH_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#ENGLISH_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.voot.com/news/cnn-news18-english-live/618600?utm_source=google_web&utm_medium=search_google_news&utm_campaign=c_website_dsa_news_performance&gclid=Cj0KCQjw7YblBRDFARIsAKkK-dKKSb4qGNhljtX6XtVA25gD8l-mHQeAIgkKpcnLhIEezVi2MoUOpEwaAg44EALw_wcB', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#ENGLISH_mobilecontainer [name="mobilebutton_2"]');
        $(document).off("click", '#ENGLISH_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.indiatoday.in/livetv', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#ENGLISH_mobilecontainer [name="mobilebutton_3"]');
        $(document).off("click", '#ENGLISH_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.livenewsnow.com/indian-english/news9-karnataka.html', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#ENGLISH_mobilecontainer [name="mobilebutton_4"]');
        $(document).off("click", '#ENGLISH_mobilecontainer [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.republicworld.com/livetv', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#ENGLISH_mobilecontainer [name="mobilebutton_5"]');
        $(document).off("click", '#ENGLISH_mobilecontainer [name="mobilebutton_6"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://www.timesnownews.com/livetv', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');
                }
            },
        }, '#ENGLISH_mobilecontainer [name="mobilebutton_6"]');
    };
    $(document).off("pagebeforeshow", "#ENGLISH").on("pagebeforeshow", "#ENGLISH", function(event, ui) {
        Apperyio.CurrentScreen = "ENGLISH";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    ENGLISH_onLoad();
};
$(document).off("pagecreate", "#ENGLISH").on("pagecreate", "#ENGLISH", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ENGLISH_js();
});