/*
 * JS for LANGUAGESELECTION generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '4755af2a-9649-4082-8a4e-5a002094efea';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "SELECT",
    "location": "SELECT.html"
}, {
    "name": "MAPS",
    "location": "MAPS.html"
}, {
    "name": "LANGUAGESELECTION",
    "location": "LANGUAGESELECTION.html"
}, {
    "name": "TELUGU",
    "location": "TELUGU.html"
}, {
    "name": "HINDI",
    "location": "HINDI.html"
}, {
    "name": "ENGLISH",
    "location": "ENGLISH.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "TAMIL",
    "location": "TAMIL.html"
}];

function LANGUAGESELECTION_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'LANGUAGESELECTION_mobilebutton_2',
        'mobilebutton_3': 'LANGUAGESELECTION_mobilebutton_3',
        'mobilebutton_4': 'LANGUAGESELECTION_mobilebutton_4',
        'mobilebutton_5': 'LANGUAGESELECTION_mobilebutton_5'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'LANGUAGESELECTION';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var LANGUAGESELECTION_onLoad = function() {
        LANGUAGESELECTION_elementsExtraJS();
        LANGUAGESELECTION_deviceEvents();
        LANGUAGESELECTION_windowEvents();
        LANGUAGESELECTION_elementsEvents();
    };
    // screen window events
    function LANGUAGESELECTION_windowEvents() {
        $('#LANGUAGESELECTION').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function LANGUAGESELECTION_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function LANGUAGESELECTION_elementsExtraJS() {
        // screen (LANGUAGESELECTION) extra code
    };
    // screen elements handler
    function LANGUAGESELECTION_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('TAMIL', {
                        transition: 'fade',
                        reverse: false
                    });
                }
            },
        }, '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_2"]');
        $(document).off("click", '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ENGLISH', {
                        reverse: false
                    });
                }
            },
        }, '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_3"]');
        $(document).off("click", '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('HINDI', {
                        reverse: false
                    });
                }
            },
        }, '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_4"]');
        $(document).off("click", '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_5"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('TELUGU', {
                        reverse: false
                    });
                }
            },
        }, '#LANGUAGESELECTION_mobilecontainer [name="mobilebutton_5"]');
    };
    $(document).off("pagebeforeshow", "#LANGUAGESELECTION").on("pagebeforeshow", "#LANGUAGESELECTION", function(event, ui) {
        Apperyio.CurrentScreen = "LANGUAGESELECTION";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    LANGUAGESELECTION_onLoad();
};
$(document).off("pagecreate", "#LANGUAGESELECTION").on("pagecreate", "#LANGUAGESELECTION", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    LANGUAGESELECTION_js();
});