/*
 * JS for MAPS generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '4755af2a-9649-4082-8a4e-5a002094efea';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "SELECT",
    "location": "SELECT.html"
}, {
    "name": "MAPS",
    "location": "MAPS.html"
}, {
    "name": "LANGUAGESELECTION",
    "location": "LANGUAGESELECTION.html"
}, {
    "name": "TELUGU",
    "location": "TELUGU.html"
}, {
    "name": "HINDI",
    "location": "HINDI.html"
}, {
    "name": "ENGLISH",
    "location": "ENGLISH.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "TAMIL",
    "location": "TAMIL.html"
}];

function MAPS_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'MAPS_mobilebutton_2',
        'mobiletextinput_5': 'MAPS_mobiletextinput_5',
        'mobiletextinput_4': 'MAPS_mobiletextinput_4',
        'googlemap_6': 'MAPS_googlemap_6',
        'marker_7': 'MAPS_marker_7'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["MAPS_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "MAPS",
        "directions": [
            {
                "from_name": "geolocation1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "MAPS",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['coords']['latitude']",
                        "target": "$['mobiletextinput_5:text']"
                    },
                    {
                        "source": "$['data']['coords']['longitude']",
                        "target": "$['mobiletextinput_4:text']"
                    },
                    {
                        "source": "$['data']['coords']['latitude']",
                        "target": "$['googlemap_6:latitude']"
                    },
                    {
                        "source": "$['data']['coords']['longitude']",
                        "target": "$['googlemap_6:longitude']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["MAPS_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "MAPS",
        "directions": [
            {
                "to_name": "geolocation1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "options": {
                            "maximumAge": 3000,
                            "timeout": 5000,
                            "enableHighAccuracy": true,
                            "watchPosition": false
                        }
                    }
                },
                "mappings": []
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["MAPS_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["MAPS_geolocation1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'MAPS';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var MAPS_onLoad = function() {
        MAPS_elementsExtraJS();
        MAPS_deviceEvents();
        MAPS_windowEvents();
        MAPS_elementsEvents();
    };
    // screen window events
    function MAPS_windowEvents() {
        $('#MAPS').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function MAPS_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function MAPS_elementsExtraJS() {
        // screen (MAPS) extra code
        /* googlemap_6 */
        $("[name = 'googlemap_6']").wrap("<div/>");
        $("[name = 'googlemap_6']").parent().css("margin-left", $("[name = 'googlemap_6']").css("margin-left"));
        $("[name = 'googlemap_6']").parent().css("margin-right", $("[name = 'googlemap_6']").css("margin-right"));
        $("[name = 'googlemap_6']").css("margin-left", '0');
        $("[name = 'googlemap_6']").css("margin-right", '0');
        var googlemap_6_options = {
            markerSourceName: "googlemap_6_markers",
            latitude: "",
            longitude: "",
            address: "San Francisco, CA",
            zoom: 10,
            showLocationMarker: true
        }
        Apperyio.__registerComponent('googlemap_6', new Apperyio.ApperyMapComponent("googlemap_6", googlemap_6_options));
        $("[name='googlemap_6_markers'] [apperytype='marker']").attr("reRender", "googlemap_6");

        function __update_googlemap_6(event, ui) {
            if (($('#MAPS_googlemap_6', ui.toPage).length > 0) && (Apperyio('googlemap_6') != undefined) && (Apperyio('googlemap_6').isInitialized)) {
                Apperyio('googlemap_6').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.MAPS_mobilecontainer", __update_googlemap_6).on("pagecontainershow.MAPS_mobilecontainer", __update_googlemap_6);
    };
    // screen elements handler
    function MAPS_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#MAPS_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#MAPS_mobileheader [name="mobilebutton_2"]');
    };
    $(document).off("pagebeforeshow", "#MAPS").on("pagebeforeshow", "#MAPS", function(event, ui) {
        Apperyio.CurrentScreen = "MAPS";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    MAPS_onLoad();
};
$(document).off("pagecreate", "#MAPS").on("pagecreate", "#MAPS", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    MAPS_js();
});