/*
 * JS for SELECT generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '4755af2a-9649-4082-8a4e-5a002094efea';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "SELECT",
    "location": "SELECT.html"
}, {
    "name": "MAPS",
    "location": "MAPS.html"
}, {
    "name": "LANGUAGESELECTION",
    "location": "LANGUAGESELECTION.html"
}, {
    "name": "TELUGU",
    "location": "TELUGU.html"
}, {
    "name": "HINDI",
    "location": "HINDI.html"
}, {
    "name": "ENGLISH",
    "location": "ENGLISH.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "TAMIL",
    "location": "TAMIL.html"
}];

function SELECT_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'SELECT_mobilebutton_2',
        'mobilebutton_3': 'SELECT_mobilebutton_3'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'SELECT';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var SELECT_onLoad = function() {
        SELECT_elementsExtraJS();
        SELECT_deviceEvents();
        SELECT_windowEvents();
        SELECT_elementsEvents();
    };
    // screen window events
    function SELECT_windowEvents() {
        $('#SELECT').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function SELECT_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function SELECT_elementsExtraJS() {
        // screen (SELECT) extra code
    };
    // screen elements handler
    function SELECT_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#SELECT_mobilecontainer [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('LANGUAGESELECTION', {
                        reverse: false
                    });
                }
            },
        }, '#SELECT_mobilecontainer [name="mobilebutton_2"]');
        $(document).off("click", '#SELECT_mobilecontainer [name="mobilebutton_3"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('MAPS', {
                        transition: 'fade',
                        reverse: false
                    });
                }
            },
        }, '#SELECT_mobilecontainer [name="mobilebutton_3"]');
    };
    $(document).off("pagebeforeshow", "#SELECT").on("pagebeforeshow", "#SELECT", function(event, ui) {
        Apperyio.CurrentScreen = "SELECT";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    SELECT_onLoad();
};
$(document).off("pagecreate", "#SELECT").on("pagecreate", "#SELECT", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    SELECT_js();
});